sudo: false

language: python

python:
  # - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly" # currently points to 3.6-dev
  #- "pypy"
  - "pypy3"

install:
    - pip install -U coverage
    - pip install codecov

script:
    - coverage -m tests
    #- coverage --branch -m tests

after_success:
    - codecov
