sudo: false

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy"
  - "pypy3"

install:
  - pip install argcomplete
  - pip install -U coverage
  - pip install enum-compat
  - pip install codecov

script:
  - coverage run --branch --omit='tests/*',setup.py --source . -m tests -v

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION = '3.7' ]]; then codecov; fi
