# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '2 1 1 * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        include:
          - os: windows-latest
            python-version: 3.9
          - os: macos-latest
            python-version: 3.9

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=80 --statistics
    - name: Build and install hashsum
      run: |
        python setup.py sdist --formats=gztar
        python -m pip wheel -w dist dist/hashsum-*.tar.gz
        python -m pip install dist/hashsum*.whl
      shell: bash
    - name: Test CLI
      if: ${{ matrix.os != 'windows-latest' }}
      run: |
        which hashsum
        hashsum -h
    - name: Test with pytest
      run: |
        pytest -Werror --cov=hashsum --cov-report=xml
    - name: Codecov
      uses: codecov/codecov-action@v1
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
